Name:Srujan Nalawade

PRN:25070123140

Batch: ENTC-A1

#Experiment-9
#Study of Pandas Library(UNIT-2)

In [11]:
#Panda
'''Used for:
Structured data
EDA
Data Cleaning'''

'Used for:\nStructured data\nEDA\nData Cleaning'

In [12]:
import pandas as pd
s = pd.Series([10,20,30,40])
s

0    10
1    20
2    30
3    40
dtype: int64

In [13]:
#Create DataFrame
data={
    "Name":["A","B","C"],
    "Marks":[85,95,69]
}
df=pd.DataFrame(data)
df

  Name  Marks
0    A     85
1    B     95
2    C     69

In [14]:
df.head()
df.tail()

  Name  Marks
0    A     85
1    B     95
2    C     69

In [15]:
#Find the structure of the DataFrame
df.shape

(3, 2)

In [16]:
df.ndim #(num of features-columns)

2

In [30]:
df.size
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Marks   3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

In [18]:
#Display of Columns Names
df.columns

Index(['Name', 'Marks'], dtype='object')

In [19]:
#Check Data Types of Each Column
df.dtypes

Name     object
Marks     int64
dtype: object

In [20]:
#Access Individual Column
df["Marks"]

0    85
1    95
2    69
Name: Marks, dtype: int64

In [21]:
#access specific row
df.loc[1]

Name      B
Marks    95
Name: 1, dtype: object

In [22]:
df.loc[2]

Name      C
Marks    69
Name: 2, dtype: object

In [23]:
# Add a new Column
df["Grade"] = ["First Class","Distinction","Second Class"]
df

  Name  Marks         Grade
0    A     85   First Class
1    B     95   Distinction
2    C     69  Second Class

In [24]:
#Update a data
df.loc[0,"Marks"]=87
df

  Name  Marks         Grade
0    A     87   First Class
1    B     95   Distinction
2    C     69  Second Class

In [25]:
#Delete a column
df.drop("Grade",axis=1, inplace=True)
df

  Name  Marks
0    A     87
1    B     95
2    C     69

In [26]:
#perform statistical analysis
df["Marks"].mean()

np.float64(83.66666666666667)

In [27]:
df['Marks'].min()

69

In [28]:
df['Marks'].max()

95

In [29]:
#Apply Condition(Filtering)
#Display Students scoring more than 80.
df[df['Marks']>80]

  Name  Marks
0    A     87
1    B     95